config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :authors
  resources :categories
  resources :books
  resources :comments
  root 'books#index'

end

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href=<%= books_path %>>Book Store Online</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href=<%= books_path%>>Home</a></li>
        
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" >Categories
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            
            <% categories.each do |category| %>
              <li><a href=<%= category_path(category) %>><%= category.name %></a><li>
            <% end %>
            <% if current_user.try(:admin?) %>
            <li class="divider"></li>
            <li><a role="menuitem" tabindex="-1" href=<%= categories_path %>> All</a></li>
            <% end %>
          
          </ul>
        </li>
        
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown">Authors
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% authors.each do |author| %>
              <li><a href=<%= author_path(author) %>><%= author.name %></a><li>
            <% end %>
            <% if current_user.try(:admin?) %>
            <li class="divider"></li>
            <li><a role="menuitem" tabindex="-1" href=<%= authors_path %>> All</a></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><a href=<%= edit_user_registration_path %>><span class="glyphicon glyphicon-user"></span><%= current_user.email %></a><li>
            <li><a href=<%= destroy_user_session_path %> data-method="delete" ><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
        <% else %>
            <li><a href=<%= new_user_registration_path %>><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href=<%= new_user_session_path %>><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>    
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>

  <%= render 'layouts/top_nav' , categories: @categories , authors: @authors %>

</br>
</br>
</br>
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button class="close" data-dismiss="alert">x</button>
      <%= flash[:notice] %>
    </div>
  <% end %>
  
  <% if flash[:alert] %>
      <div class="alert alert-danger">
        <button class="close" data-dismiss="alert">x</button>
        <%= flash[:alert] %>
      </div>
  <% end %>
  
  <%= yield %>
</div>

</body>
</html>